FROM quay.io/quarkus/ubi-quarkus-native-image:latest AS build
WORKDIR /project
COPY . /project
RUN ./mvnw -Pnative -Dquarkus.native.container-build=true clean package

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6
WORKDIR /work/
COPY --from=build /project/target/*-runner /work/application
RUN chmod 0755 /work/application
EXPOSE 8080
USER 1001
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
